---
title: "Practical 2"
execute: 
  freeze: auto
format: 
  html:
    mainfont: "12"
  PrettyPDF-pdf:
    keep-tex: false
    number-sections: true
embed-resources: true
editor_options: 
  chunk_output_type: console
---

```{r}
#| echo: false
#| message: false
#| warning: false
#| purl: false
#| results: hide
#| eval: true
library(webexercises)
knitr::purl("day1_practical_2.qmd")
```

<font size="5"> **Aim of this practical:** </font>

1.  Set priors for different linear models
2.  Compute and visualize posterior densities and summaries for marginal effects
3.  Fit hierarchical flexible models

we are going to learn:

-   How to change some of the R default priors in `inlabru`
-   How to explore and visualize model parameters
-   Fit different flexible models

{{< downloadthis day1_practical_2.R dname="practical_2.R" label="Download Practical 2 R script" icon="database-fill-down" type="success" >}}

```{r child="practicals/LM_ex_priors.qmd"}
```

```{r child="practicals/LMM_fish_example.qmd"}
```
