---
title: "Practical 3"
format: 
  html: default
  PrettyPDF-pdf:
    keep-tex: true
    number-sections: true
embed-resources: true
editor_options: 
  chunk_output_type: console
---

```{r}
#| echo: false
#| message: false
#| warning: false
#| purl: false
#| results: hide
library(webexercises)
knitr::purl("day1_practical.qmd")
```

<font size="5"> **Aim of this practical:** </font> In this first practical we are going to look at some simple models

1.  A Gaussian model with simulated data
2.  A Linear mixed model
3.  A GLM model with random effects

we are going to learn:

-   How to fit some commonly used models with `inlabru`
-   How to explore the results
-   How to get predictions for missing data points

{{< downloadthis day1_practical.R dname="practical_1.R" label="Download Practical 1 R script" icon="database-fill-down" type="success" >}}

```{r child="C:\\Users\\jaf_i\\OneDrive\\Documentos\\inlabru_worhsop\\inlabru_workshop\\docs\\practicals\\LM_ex.qmd"}
```

```{r child="C:\\Users\\jaf_i\\OneDrive\\Documentos\\inlabru_worhsop\\inlabru_workshop\\docs\\practicals\\LMM_ex.qmd"}
```

```{r child="C:\\Users\\jaf_i\\OneDrive\\Documentos\\inlabru_worhsop\\inlabru_workshop\\docs\\practicals\\GLM_ex.qmd"}
```

```{r child="C:\\Users\\jaf_i\\OneDrive\\Documentos\\inlabru_worhsop\\inlabru_workshop\\docs\\practicals\\GAM_ex.qmd"}
```
