---
title: "Lecture 1"
subtitle: Spatial Modelling with `inlabru`
author:
  - name: Sara Martino
    # email: Jafet.BelmontOsuna@glasgow.ac.uk
    affiliations: Norwegian University of Science and Technology
  - name: Janine Illian
  - affiliations: University of Glasgow
format:
  revealjs:
    margin: 0
    logo:  UofG.png
    theme: uofg_theme.scss
    header-includes: |
      <script src="custom.js" type="application/javascript"></script>
title-slide-attributes: 
  data-background-color: "#f1f1f1"
slide-number: true
date: 12/15/2025
date-format: long
execute: 
  eval: true
  echo: true
embed-resources: true
editor_options: 
  chunk_output_type: console
---


# Welcome to the course

## Course Structure: Day 1 {.smaller}

+-------------+---------------------+----------------------------+------------+
| Time        | Topic               | Content                    | Excercises |
+=============+=====================+============================+============+
| **XXXX am** | **Core concepts**   | -   LGM and INLA           |            |
|             |                     |                            |            |
|             |                     | -   inlabru workflow       |            |
|             |                     |                            |            |
|             |                     | -   Model selection        |            |
+-------------+---------------------+----------------------------+------------+
| XXXX am     | **Temporal Models** | -   Discrete time models   |            |
|             |                     |                            |            |
|             |                     | -   Continuous time models |            |
+-------------+---------------------+----------------------------+------------+

## Course Structure: Day 2 {.smaller}

+-------------+---------------------------------------+--------------------------------------------------------------------+------------+
| Time        | Topic                                 | Content                                                            | Excercises |
+=============+=======================================+====================================================================+============+
| **XXXX am** | **Introduction to Spatial Modelling** | -   Types of spatial data                                         |            |
|             |                                       |                                                                   |            |
|             |                                       | -   Spatial data wrangling and manipulation in R (e.g., terra & sf) |       |
|             |                                       |                                                                   |            |
|             |                                       | -   Areal processes                                               |            |
+-------------+---------------------------------------+--------------------------------------------------------------------+------------+
| XXXX am     | **Modelling geostatistical data**     | -   SPDE & the mesh                                                |            |
|             |                                       |                                                                    |            |
|             |                                       | -   Geostatistical data                                            |            |
|             |                                       |                                                                    |            |
|             |                                       | -   Spatial predictions                                            |            |
+-------------+---------------------------------------+--------------------------------------------------------------------+------------+

## Course Structure: Day 3 {.smaller}

+-------------+-----------------------------+-------------------------------------+------------+
| Time        | Topic                       | Content                             | Excercises |
+=============+=============================+=====================================+============+
| **XXXX am** | **Spatial Point processes** | -   Spatial point processes         |            |
|             |                             |                                     |            |
|             |                             | -   detectability,Distance sampling |            |
+-------------+-----------------------------+-------------------------------------+------------+
| XXXX am     | **Spatiotemporal Models**   | -   Separable time-space models     |            |
|             |                             |                                     |            |
|             |                             | -   non-separable space-time models |            |
+-------------+-----------------------------+-------------------------------------+------------+

## Course Structure: Day 4 {.smaller}

+-------------+-------------------------------------------+-------------------------------+------------+
| Time        | Topic                                     | Content                       | Excercises |
+=============+===========================================+===============================+============+
| **XXXX am** | **Multilikelihood and Non-linear models** | -   iterated inla             |            |
|             |                                           |                               |            |
|             |                                           | -   logistic growth           |            |
|             |                                           |                               |            |
|             |                                           | -   Corregionalization models |            |
+-------------+-------------------------------------------+-------------------------------+------------+
