---
title: "List of changes"
output: html_document
date: "2025-10-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## List of changes

+---------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Document            | Owner/Creator | Description of change(s)                                                                                                                                                                                                         | Track of changes |
+=====================+===============+==================================================================================================================================================================================================================================+==================+
| Areal_ex.qmd        | Sara          | 1.  Add covariates (e.g., `pm10`) to the CAR model. (if this changes then update the questions answers)                                                                                                                          |                  |
|                     |               |                                                                                                                                                                                                                                  |                  |
|                     |               | 2.  Why not considering BYM2 instead of traditional BYM?                                                                                                                                                                         |                  |
|                     |               |                                                                                                                                                                                                                                  |                  |
|                     |               | 3.  Hint on the last task (comparing predicted vs. observed counts) is missing.                                                                                                                                                  |                  |
+---------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| Geostat_ex.qmd      | Sara          | 1.  Maybe add a question where different meshes are constructed and ask which one is good or a bad mesh                                                                                                                          |                  |
|                     |               | 2.  For the question about the spde model, maybe add some possible answers (I added some but I think a practical hint is needed, e.g., how can participants know the extent or the spatial resolution to make a sensible choice) |                  |
|                     |               | 3.  The hints for the Task about prediction using the coordinates of the covariate is missing. Also I find this a bit confusing since we haven't use the covariate yet, maybe move this bit to the alternative model section?    |                  |
|                     |               | 4.  Hint for the model with a linear covariate is missing.                                                                                                                                                                       |                  |
+---------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
| PointProcess_ex.qmd | Sara          | 1.  On the first task about plotting the posterior intensity, add a reminder of `inla.tmarginal` in the Hint                                                                                                                     |                  |
+---------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
|                     |               |                                                                                                                                                                                                                                  |                  |
+---------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
|                     |               |                                                                                                                                                                                                                                  |                  |
+---------------------+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+
